#!/usr/bin/env python3
"""
Generate a Markdown comparison report from test results.
Reads all JSON results and produces a formatted report.

Usage:
    python3 generate-report.py [results_dir] [output_file]
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

RESULTS_DIR = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).resolve().parent.parent / "results"
OUTPUT_FILE = Path(sys.argv[2]) if len(sys.argv) > 2 else RESULTS_DIR / "report.md"


def load_results():
    results = {}
    for f in sorted(RESULTS_DIR.glob("*.json")):
        if f.name in ("comparison.md", "report.md"):
            continue
        try:
            with open(f) as fh:
                data = json.load(fh)
                results[data.get("tool", f.stem)] = data
        except (json.JSONDecodeError, KeyError):
            pass
    return results


def best_mode_stats(data):
    agg = data.get("aggregate", {})
    for mode in ["hybrid", "vector", "bm25"]:
        if mode in agg and agg[mode].get("mrr", 0) > 0:
            return mode, agg[mode]
    return "N/A", {"hit_at_1": 0, "hit_at_3": 0, "mrr": 0, "median_latency_ms": 0}


def generate_report(results):
    lines = []
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    tools = sorted(results.keys())

    lines.append("# KINDX Competitor Comparison Report")
    lines.append(f"\nGenerated: {now}")
    lines.append(f"\nTools tested: {len(results)}")
    lines.append("")

    # Executive summary
    lines.append("## Executive Summary\n")
    kindx_data = results.get("kindx", {})
    if kindx_data:
        _, stats = best_mode_stats(kindx_data)
        lines.append(f"KINDX achieves **{stats.get('mrr', 'N/A')} MRR** in hybrid mode with "
                      f"**{stats.get('median_latency_ms', 'N/A')}ms** median latency, while being "
                      f"the only tool that combines BM25 + vector + hybrid search with native MCP, "
                      f"CLI-first design, and structured output (JSON/CSV/XML) — all in a single "
                      f"`npm install`.")
    lines.append("")

    # Retrieval quality table
    lines.append("## Retrieval Quality\n")
    lines.append("| Tool | Best Mode | Hit@1 | Hit@3 | MRR | Median Latency |")
    lines.append("|------|-----------|-------|-------|-----|----------------|")

    rows = []
    for tool in tools:
        mode, stats = best_mode_stats(results[tool])
        rows.append((tool, mode, stats))

    rows.sort(key=lambda r: r[2].get("mrr", 0), reverse=True)
    for tool, mode, stats in rows:
        lat = stats.get("median_latency_ms", 0)
        lat_str = f"{lat}ms" if lat > 0 else "N/A"
        lines.append(f"| **{tool}** | {mode} | {stats.get('hit_at_1', 0)} | "
                      f"{stats.get('hit_at_3', 0)} | {stats.get('mrr', 0)} | {lat_str} |")
    lines.append("")

    # Capability matrix
    lines.append("## Capabilities\n")
    caps = [
        ("BM25/Keyword", "bm25"),
        ("Vector/Semantic", "vector"),
        ("Hybrid Search", "hybrid"),
        ("Reranking", "reranking"),
        ("Native MCP Server", "mcp_server"),
        ("CLI Query", "cli_query"),
        ("JSON Output", "json_output"),
        ("CSV Output", "csv_output"),
        ("XML Output", "xml_output"),
        ("Agent-Invocable", "agent_invocable"),
        ("Air-Gapped/Local", "air_gapped"),
        ("Local GGUF", "local_gguf"),
    ]

    header = "| Feature | " + " | ".join(tools) + " |"
    sep = "|---------|" + "|".join([":-:" for _ in tools]) + "|"
    lines.append(header)
    lines.append(sep)

    for label, key in caps:
        row = f"| {label} |"
        for tool in tools:
            val = results[tool].get("capabilities", {}).get(key, False)
            row += " Yes |" if val else " - |"
        lines.append(row)
    lines.append("")

    # Setup friction
    lines.append("## Setup Friction\n")
    lines.append("| Tool | Steps | Install Time | Models (MB) |")
    lines.append("|------|-------|-------------|-------------|")

    setup_rows = []
    for tool in tools:
        setup = results[tool].get("setup", {})
        setup_rows.append((
            tool,
            setup.get("total_setup_steps", 0),
            setup.get("install_time_seconds", 0),
            setup.get("models_downloaded_mb", 0),
        ))
    setup_rows.sort(key=lambda r: r[1])
    for tool, steps, time_s, models in setup_rows:
        lines.append(f"| **{tool}** | {steps} | {time_s}s | {models}MB |")
    lines.append("")

    # Notes
    lines.append("## Notes\n")
    for tool in tools:
        notes = results[tool].get("notes", "")
        if notes:
            lines.append(f"- **{tool}**: {notes}")
    lines.append("")

    lines.append("---")
    lines.append(f"*Report generated by KINDX comparison framework on {now}*")

    return "\n".join(lines)


def main():
    results = load_results()
    if not results:
        print("No results found. Run tests first.")
        sys.exit(0)

    report = generate_report(results)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        f.write(report)

    print(f"Report generated: {OUTPUT_FILE}")
    print(f"Tools included: {', '.join(sorted(results.keys()))}")


if __name__ == "__main__":
    main()
