name: Linked Issue Enforcer

on:
  pull_request:
    types: [opened, edited]

concurrency:
  group: linked-issue-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  check-linked-issue:
    name: Require Linked Issue
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.actor != 'release-please[bot]'
    permissions:
      pull-requests: read

    steps:
      - name: Check for linked issue
        uses: nearform-actions/github-action-check-linked-issues@v1
        with:
          exclude-branches: "release-please--*,dependabot/**"
